import type { LibMeta, LibEsmResult } from './type';
import libEsm from 'lib-esm';

interface AntdPreset {
  v4: string;
}
const antd_v4: LibMeta = {
  name: 'antd',
  members: [
    'Affix',
    'Anchor',
    'AutoComplete',
    'Alert',
    'Avatar',
    'BackTop',
    'Badge',
    'Breadcrumb',
    'Button',
    'Calendar',
    'Card',
    'Collapse',
    'Carousel',
    'Cascader',
    'Checkbox',
    'Col',
    'Comment',
    'ConfigProvider',
    'DatePicker',
    'Descriptions',
    'Divider',
    'Dropdown',
    'Drawer',
    'Empty',
    'Form',
    'Grid',
    'Input',
    'Image',
    'InputNumber',
    'Layout',
    'List',
    'message',
    'Menu',
    'Mentions',
    'Modal',
    'Statistic',
    'notification',
    'PageHeader',
    'Pagination',
    'Popconfirm',
    'Popover',
    'Progress',
    'Radio',
    'Rate',
    'Result',
    'Row',
    'Select',
    'Skeleton',
    'Slider',
    'Space',
    'Spin',
    'Steps',
    'Switch',
    'Table',
    'Transfer',
    'Tree',
    'TreeSelect',
    'Tabs',
    'Tag',
    'TimePicker',
    'Timeline',
    'Tooltip',
    'Typography',
    'Upload',
    'version',
  ],
};

const v4_result: LibEsmResult = libEsm({
  window: antd_v4.name,
  exports: antd_v4.members,
});

export const antd: AntdPreset = {
  v4: `${v4_result.window}\n${v4_result.exports}`,
};
