import type { LibMeta, LibEsmResult } from './type';
import libEsm from 'lib-esm';

interface ElementUiPreset {
  v2: string;
}

const element_ui_v2: LibMeta = {
  name: 'ELEMENT',
  members: [
    'version',
    'locale',
    'i18n',
    'install',
    'CollapseTransition',
    'Loading',
    'Pagination',
    'Dialog',
    'Autocomplete',
    'Dropdown',
    'DropdownMenu',
    'DropdownItem',
    'Menu',
    'Submenu',
    'MenuItem',
    'MenuItemGroup',
    'Input',
    'InputNumber',
    'Radio',
    'RadioGroup',
    'RadioButton',
    'Checkbox',
    'CheckboxButton',
    'CheckboxGroup',
    'Switch',
    'Select',
    'Option',
    'OptionGroup',
    'Button',
    'ButtonGroup',
    'Table',
    'TableColumn',
    'DatePicker',
    'TimeSelect',
    'TimePicker',
    'Popover',
    'Tooltip',
    'MessageBox',
    'Breadcrumb',
    'BreadcrumbItem',
    'Form',
    'FormItem',
    'Tabs',
    'TabPane',
    'Tag',
    'Tree',
    'Alert',
    'Notification',
    'Slider',
    'Icon',
    'Row',
    'Col',
    'Upload',
    'Progress',
    'Spinner',
    'Message',
    'Badge',
    'Card',
    'Rate',
    'Steps',
    'Step',
    'Carousel',
    'Scrollbar',
    'CarouselItem',
    'Collapse',
    'CollapseItem',
    'Cascader',
    'ColorPicker',
    'Transfer',
    'Container',
    'Header',
    'Aside',
    'Main',
    'Footer',
    'Timeline',
    'TimelineItem',
    'Link',
    'Divider',
    'Image',
    'Calendar',
    'Backtop',
    'InfiniteScroll',
    'PageHeader',
    'CascaderPanel',
    'Avatar',
    'Drawer',
    'Popconfirm',
    'Skeleton',
    'SkeletonItem',
    'Empty',
    'Descriptions',
    'DescriptionsItem',
    'Result',
  ],
};

const v2_result: LibEsmResult = libEsm({
  window: element_ui_v2.name,
  exports: element_ui_v2.members,
});

export const element_ui: ElementUiPreset = {
  v2: `${v2_result.window}\n${v2_result.exports}`,
};
